
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainHeader from "../Components/layout/Header/MainHeader";
import MainFooter from "@/Components/layout/Footer/MainFooter";
import TanstackQueryProvider from "@/Components/partials/provider/TanstackQueryProvider";
import CustomToaster from "@/Components/atoms/CustomToaster";
import CustomScrollbar from "../Components/atoms/CustomScrollbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "torino",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TanstackQueryProvider>
          
          <CustomScrollbar
            style={{
              height: "100vh", 
              backgroundColor: "#fff",
            }}
          >
            <MainHeader />
            <main>{children}</main>
            <MainFooter />
          </CustomScrollbar>
        </TanstackQueryProvider>

        <CustomToaster />
      </body>
    </html>
  );
}
